### ISSUE TITLE
Lab 3 Notes

### ISSUE THREAD

**Issue by AntonC9018** [ArtikusHG/uni_lab#2]
https://github.com/ArtikusHG/uni_lab/blob/4d06652787881ed19265a5c141c5fccfbbcf86a3/lab3.md?plain=1#L27
Декларировано = объявлено. Задейфайнено = определено. Терминологию попутал.

https://github.com/ArtikusHG/uni_lab/blob/4d06652787881ed19265a5c141c5fccfbbcf86a3/lab3.md?plain=1#L19
Можешь по одной паре бактиков писать.

https://github.com/ArtikusHG/uni_lab/blob/4d06652787881ed19265a5c141c5fccfbbcf86a3/lab3.md?plain=1#L196
0 потому что переменная локальная, а не потому что `void`.

https://github.com/ArtikusHG/uni_lab/blob/4d06652787881ed19265a5c141c5fccfbbcf86a3/lab3.md?plain=1#L204
Перепутал файл. Просилось `static_1.cpp`

**Comment by ArtikusHG** [comment]
Спасибо, исправил!
